### ISSUE TITLE
[EET] Restore & Tweak Soundsets generally restore rare selects to the SELECT_ACTION4-7 slots.

### ISSUE THREAD

**Issue by GraionDilach** [skellytz/infinity-sounds#7]
Now I don't remember how ToBExAL handles it (iirc the last time it defaulted to mixed mode), but this is wrong for BG2EE & EET where these alots are at CRE 0x1D0 and onwards (although EET itself might also make this mistake during importing, that's something I'll check).

**Comment by skellytz** [comment]
Thanks! Let's focus on the affected BG1 creatures from EET, because BG2 creature soundsets weren't properly designed for this slot to work (it was disabled in the game engine) and were mostly filled with invalid or some leftover strings from templates that didn't match. I admit I'd simply forgotten about rare sounds in EET. You can tell BGT was my priority, and TobExAL comes with a curated list of BG1 creatures that get the original BG1 rare sound slot behavior. This is why I need reports like this to improve EET compatibility 😉

For EET, I'll add a patch to "Restore & Tweak Soundsets" that moves these sounds to the rare slots supported by the BG2EE engine.

**Comment by GraionDilach** [comment]
> TobExAL comes with a curated list of BG1 creatures that get the original BG1 rare sound slot behavior

Yeah, I forgot about that list.

And I'll ensure that EET migrates the soundslots during BGEE import so that Infinity Sounds only needs to concentrate on the changes it wants to introduce.
